# A dictionary of mild illnesses and their traditional herbal remedies
# Disclaimer: For informational purposes only. Consult a professional before use.

herbal_remedies = {
    "Common Cold": "Ginger tea helps reduce inflammation and clear congestion.",
    "Dry Cough": "Marshmallow root tea coats the throat to reduce irritation.",
    "Wet Cough": "Thyme tea acts as an expectorant to help clear mucus.",
    "Sore Throat": "Sage tea or gargle is used to soothe throat pain.",
    "Nasal Congestion": "Eucalyptus oil steam inhalation helps open blocked airways.",
    "Mild Fever": "Catnip tea is traditionally used to promote sweating.",
    "Hay Fever": "Stinging nettle may reduce the severity of allergic reactions.",
    "Hoarseness": "Pineapple juice contains bromelain to help reduce vocal cord swelling.",
    "Seasonal Allergies": "Butterbur is often used as a natural antihistamine.",
    "Indigestion": "Peppermint tea helps relax stomach muscles and ease gas.",
    "Nausea": "Ginger is widely recognized for relieving various forms of nausea.",
    "Bloating": "Fennel seeds help relax gastrointestinal muscles to release gas.",
    "Mild Constipation": "Dandelion root acts as a gentle tonic to support bowel movements.",
    "Acute Constipation": "Senna acts as a potent natural stimulant laxative.",
    "Heartburn": "Slippery Elm coats the esophagus to soothe acid reflux.",
    "Stomach Cramps": "Chamomile tea helps reduce muscle spasms in the gut.",
    "Mild Diarrhea": "Bael fruit is a traditional remedy for settling loose bowels.",
    "Loss of Appetite": "Coriander is used as a digestive stimulant to improve appetite.",
    "Flatulence": "Ajwain (carom seeds) is a common remedy for relieving trapped gas.",
    "Motion Sickness": "Ginger is frequently used to prevent nausea during travel.",
    "IBS Symptoms": "Peppermint oil capsules are used to reduce colon spasms.",
    "Mild Hemorrhoids": "Witch Hazel is applied topically to reduce swelling and itching.",
    "Minor Burns": "Aloe Vera gel cools the skin and accelerates healing.",
    "Sunburn": "Calendula cream helps soothe red, irritated skin.",
    "Acne": "Tea tree oil acts as an antiseptic to clear bacterial skin infections.",
    "Mild Eczema": "Chamomile cream can reduce localized inflammation and itching.",
    "Fungal Infection": "Oregano oil is used topically for its antifungal properties.",
    "Insect Bites": "Lemon Balm can be applied to soothe stings and reduce itching.",
    "Bruises": "Arnica cream is commonly used to reduce swelling and discoloration.",
    "Minor Cuts": "Yarrow is traditionally used to help stop bleeding.",
    "Dry Skin": "Olive oil serves as a natural emollient to moisturize the skin.",
    "Athlete's Foot": "Tea tree oil is a powerful remedy for fungal skin conditions.",
    "Diaper Rash": "Calendula is safe for soothing infant skin irritation.",
    "Mouth Ulcers": "Myrrh tincture can be dabbed on sores to speed healing.",
    "Cold Sores": "Lemon Balm contains antiviral properties that may inhibit the virus.",
    "Mild Anxiety": "Ashwagandha may help the body manage stress and lower cortisol.",
    "Insomnia": "Valerian root may improve sleep quality and onset time.",
    "Tension Headache": "Lavender oil inhalation may help ease stress-related headaches.",
    "Mild Depression": "St. John’s Wort may improve mood in mild cases.",
    "Mental Fatigue": "Ginkgo Biloba may improve focus and cognitive blood flow.",
    "General Stress": "Holy Basil (Tulsi) may help regulate the body's stress response.",
    "Nervousness": "Passionflower may help calm the central nervous system.",
    "Poor Memory": "Rosemary is linked to improved concentration and recall.",
    "Migraine": "Feverfew may reduce the frequency and severity of migraines.",
    "Restlessness": "Lemon Balm tea may help calm adults and children.",
    "Muscle Soreness": "Ginger may reduce muscle pain after physical exertion.",
    "Mild Joint Pain": "Turmeric may reduce inflammation in joints.",
    "Mild Arthritis": "Devil’s Claw may reduce joint inflammation and stiffness.",
    "Toothache": "Clove oil acts as a natural analgesic for dental pain.",
    "Menstrual Cramps": "Raspberry leaf tea may help ease uterine cramping.",
    "Mild Backache": "Willow Bark contains salicin, a natural precursor to aspirin.",
    "Mild Sprains": "Comfrey poultices may speed up the healing of ligaments.",
    "Mild UTI": "Cranberry prevents bacteria from sticking to the bladder wall.",
    "Water Retention": "Dandelion leaf acts as a natural diuretic.",
    "Hot Flashes": "Black Cohosh is used to manage menopausal symptoms.",
    "Eye Irritation": "Eyebright tea is used as a wash for strained or tired eyes.",
    "Gum Inflammation": "Bee Balm (Bergamot) can be used as a gargle to soothe gums.",
    "General Fatigue": "Ginseng is used as an adaptogen to boost energy levels.",
    "Hiccoughs": "Dill water is a traditional remedy for settling hiccups.",
    "Night Sweats": "Sage tea is often used to reduce excessive perspiration.",
    "Dandruff": "Rosemary oil applied to the scalp can reduce flaking.",
    "Earache (External)": "Warm Garlic oil drops may help treat minor outer ear infections.",
    "Brittle Nails": "Horsetail herb is rich in silica to strengthen nails.",
    "Morning Sickness": "Ginger root is a safe traditional remedy for pregnancy nausea.",
    "Varicose Veins": "Horse Chestnut extract is used to improve venous circulation.",
    "High Blood Sugar (Mild)": "Cinnamon may help improve insulin sensitivity.",
    "High Cholesterol": "Garlic consumption is linked to modest reductions in cholesterol.",
    "Bad Breath": "Parsley is high in chlorophyll and acts as a natural deodorizer.",
    "Poor Circulation": "Cayenne pepper can stimulate blood flow and warmth.",
    "Mild Scalp Itch": "Peppermint oil provides a cooling sensation and reduces itching.",
    "Minor Scars": "Gotu Kola supports collagen production for skin repair.",
    "Colic (Infant)": "Dill or Fennel water is used to soothe baby digestive gas.",
    "Breast Tenderness": "Evening Primrose Oil may help balance hormonal sensitivity.",
    "Puffy Eyes": "Cucumber slices or Chilled Chamomile tea bags reduce swelling.",
    "Skin Redness": "Rose water acts as a mild astringent to calm skin.",
    "Mental Fog": "Gotu Kola is used in Ayurveda to enhance mental clarity.",
    "Nosebleed": "Yarrow powder can be used to help clot minor surface bleeds.",
    "Oily Skin": "Witch Hazel acts as a natural toner to remove excess oil.",
    "Chapped Lips": "Coconut oil provides a protective moisture barrier.",
    "Sore Feet": "Epsom salt soak with Rosemary oil relieves foot fatigue.",
    "Mild Shingles Pain": "Capsaicin cream (from chili) is used for nerve pain relief.",
    "Sugar Cravings": "Gymnema Sylvestre is known as the 'sugar destroyer' in Ayurveda.",
    "Jet Lag": "Melatonin (hormonal) or Valerian can help reset sleep cycles.",
    "Overeating": "Cumin seeds help stimulate enzymes for faster digestion.",
    "Low Libido": "Maca root is used as a traditional tonic for vitality.",
    "Splinters": "Plantain leaf poultice is used to help 'draw out' foreign objects.",
    "Stiff Neck": "Apply warm Mustard seed oil to improve local circulation.",
    "Sweaty Palms": "Sage tea can be used as a soak to reduce palm perspiration.",
    "Minor Allergies": "Local Honey is sometimes used to build pollen tolerance.",
    "Acid Stomach": "Licorice root (DGL) helps soothe the stomach lining.",
    "Bile Sluggishness": "Artichoke leaf extract stimulates healthy bile flow.",
    "Post-Viral Fatigue": "Reishi mushroom is used to restore energy after illness.",
    "Weak Digestion": "Yellow Dock root is used as a bitter tonic to aid absorption.",
    "Hives": "Chickweed salve can be used to cool and soothe itchy hives.",
    "Boils": "Turmeric paste is applied topically to draw out infection.",
    "Nightmares": "Passionflower tea before bed may promote calmer dreams.",
    "Brittle Hair": "Nettle tea provides minerals essential for hair strength.",
    "Sore Gums": "Clove tea can be used as a mouthwash for its numbing effect.",
    "Dizziness (Mild)": "Ginger can help stabilize the vestibular system in some cases.",
    "Warts (Mild)": "Crushed Garlic applied daily may help clear minor warts."
}
